### ISSUE TITLE
bug duplicate method index on migration

### ISSUE THREAD

**Issue by rikky22** [Bootcamp-STMIK-Mardira-Indonesia/mardira-framework#1]
when you create a column with 2 index methods on each column, it will only run 1 index

**Comment by xietsunzao** [comment]
Fixed index cannot run multiple columns

use with array arguments
example:

`
$table->index(['role_id','token_id']);
`

check here for the update commits
https://github.com/Bootcamp-STMIK-Mardira-Indonesia/mardira-framework/commit/01feb9e0cdb0b30584ad9a071c475ee9cb43fab4

Thanks for participating using this framework
