### ISSUE TITLE
Bug can't update data with query builder

### ISSUE THREAD

**Issue by I-Fack** [Bootcamp-STMIK-Mardira-Indonesia/mardira-framework#7]
can't update data, please fix it ASAP. Thank You

**Comment by xietsunzao** [comment]
Hello @I-Fack, it's resolved, check the commit here [here](https://github.com/Bootcamp-STMIK-Mardira-Indonesia/mardira-framework/commit/a78f25760d2e52e40a1f8623e8f31636ea95560e), thank you
